#!/bin/bash
pkgu() {
	echo
	echo 'Upgrade:'
	echo
	pkg upgrade
	echo
	echo 'Auto Remove:'
	echo
	apt autoremove --purge
	echo
	apt autoclean
}

aptu() {
	echo
	echo 'dpkg:'
	echo
	dpkg --configure -a
	echo
	echo 'Fix Broken:'
	echo
	apt --fix-broken install
	echo
	apt update
	echo
	echo 'Upgrade:'
	echo
	apt upgrade
	echo
	echo 'Auto Remove:'
	echo
	apt autoremove --purge
	echo
	apt autoclean
}

pipu() {
	while true; do
		echo
		read -p "Continue to Upgrade Python Packages..... [s|Y|n]: " syn
		syn=${syn:-'y'}
		case $syn in
		[yY]*)
			pip list -o
			pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
			break
			;;
		[sS]*)
			pip list -o
			while true; do
				echo
				read -p "Upgrade now..... [Y|n]: " yn
				yn=${yn:-'y'}
				case $yn in
				[nN]*)
					echo "Aborting....."
					break
					;;
				[yY]*)
					pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
					break
					;;
				*)
					echo 'Wrong Choice.....'
					;;
				esac
			done
			break
			;;
		[nN]*)
			echo "Aborting....."
			break
			;;
		*)
			echo 'Wrong Choice.....'
			;;
		esac
	done
}

gemu() {
	echo
	echo 'Gem Upgrade:'
	echo
	gem update
}

if which pkg >/dev/null >$PREFIX/dev/null || [ -e $PREFIX/bin/pkg ]; then
	pkgu
elif which apt >/dev/null >$PREFIX/dev/null || [ -e $PREFIX/bin/apt ]; then
	aptu
fi
if which pip >/dev/null >$PREFIX/dev/null || [ -e $PREFIX/bin/python ]; then
	pipu
fi
if which gem >/dev/null >$PREFIX/dev/null || [ -e $PREFIX/bin/gem ]; then
	gemu
fi
