#!/bin/bash
RESET="\033[0m"
BOLD="\033[1m"
YELLOW="\033[0;33m"
BLUE='\033[1;94m'

pkgu() {
	echo
	printf "\n${BLUE}%s${RESET}\n" "Upgrade:"
	echo
	pkg upgrade
	echo
	echo
	echo 'Auto Remove:'
	echo
	apt autoremove --purge
	echo
	apt autoclean
}

aptu() {
	echo
	echo 'dpkg:'
	echo
	dpkg --configure -a
	echo
	echo 'Fix Broken:'
	echo
	apt --fix-broken install
	echo
	apt update
	echo
	echo 'Upgrade:'
	echo
	apt upgrade
	echo
	echo
	echo 'Auto Remove:'
	echo
	apt autoremove --purge
	echo
	apt autoclean
}
pipu() {
	while true; do
		echo
		echo
		read -p "Continue to Upgrade Python Packages..... [s|Y|n]: " syn
		syn=${syn:-'y'}
		case $syn in
		[yY]*)
			pip list -o
			pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
			break
			;;
		[sS]*)
			pip list -o
			while true; do
				echo
				read -p "Upgrade now..... [Y|n]: " yn
				yn=${yn:-'y'}
				case $yn in
				[nN]*)
					echo "Aborting....."
					break
					;;
				[yY]*)
					pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
					break
					;;
				*)
					echo 'Wrong Choice.....'
					;;
				esac
			done
			break
			;;
		[nN]*)
			echo "Aborting....."
			break
			;;
		*)
			echo 'Wrong Choice.....'
			;;
		esac
	done
}

gemu() {
	echo
	echo
	echo 'Gem Upgrade:'
	echo
	gem update
}

toolu() {
	cd $1
	echo
	printf "\n${BLUE}%s${RESET}\n" "Updating GitHub Packages("${PWD##*/}"):"
	if [ -d ".git" ]; then
		echo
		printf "${YELLOW}${BOLD}%s${RESET}\n" "${PWD##*/}"
		git pull
	fi
	for plugin in */; do
		if [ -d "$plugin/.git" ]; then
			echo
			printf "${YELLOW}${BOLD}%s${RESET}\n" "${plugin%/}"
			git -C "$plugin" pull
		fi
	done
}


if [ -e $PREFIX/bin/pkg ]; then
	pkgu
elif [ -e $PREFIX/bin/apt ]; then
	aptu
fi
if [ -e $PREFIX/bin/python ]; then
	pipu
fi
if [ -e $PREFIX/bin/gem ]; then
	gemu
fi

#GIT PACKAGES
if [ -e /etc/UGpack/ugpack.conf ]; then
	while read LINE; do
		toolu $LINE
	done < <(grep -v "^#\|^$" /etc/UGpack/ugpack.conf)
elif [ -e /data/data/com.termux/files/usr/etc/UGpack/ugpack.conf ]; then
	while read LINE; do
		toolu $LINE
	done < <(grep -v "^#\|^$" /data/data/com.termux/files/usr/etc/UGpack/ugpack.conf)
fi
